on:
  workflow_dispatch:

jobs:
  memory-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: The input step
        id: inputStep
        uses: ./
        with:
          myInput: "Manual execution from Daniel"

      - name: The output step
        run: |
          echo "${{ steps.inputStep.outputs.memory }}"
          echo "Total memory output success!"
